# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >-
  Depools Improvement Proposals (DIPs) describe standards for the depools
  platform, including core protocol specifications, client APIs, and contract
  standards.
url: "https://forum.depool.com/"
repository: depools/depools-improvement-proposals
twitter_username: depool
github_username: depool
header_pages:
  - all-dip.html
twitter:
  card: summary
  username: depool

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

permalink: /:slug

defaults:
  - scope:
      path: "DIPS"
    values:
      layout: "dip"
  - scope:
      path: ""
    values:
      image: "/assets/og_image.png"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dip-X.md
